/* eslint no-unused-vars: "off" */
const DEFAULT_APPROVED_COLOR = '#379683'
const DEFAULT_DRAFT_COLOR = '#2A4860'
const DEFAULT_OBSOLESCENCE_IN_DAY = 15
const DEFAULT_OBSOLETE_COLOR = '#E7717D'
const DEFAULT_REQUEST_CHANGES_COLOR = '#FCE3AB'
const DEFAULT_REVIEW_REQUIRED_COLOR = '#E07B39'

const store = chrome.storage.sync
