name: Node.js CI

on: push

jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this branch
        uses: actions/checkout@master
      - name: Install node modules
        run: yarn
      - name: Run the linter
        run: yarn lint
